name: RedstoneICs
main: re._1r.spigot.RedstoneICs
version: 1.0
api-version: 1.13
commands:
  set:
    desciption: Set Metadata
    usage: /<command>
  get:
    desciption: Get Metadata
    usage: /<command>