name: RedstoneICs
main: es.tmoor.minecraft.RedstoneICs
version: 1.0
api-version: 1.13
commands:
  compile:
    desciption: Compile the contents of a held book & assign them to the book
    usage: /<command>